### ISSUE TITLE
The application “AltServer.app” can’t be opened.

### ISSUE THREAD

**Issue by naturale0** [iftekharAmurad/altstore#4]
Hi,

1.5b8 version of AltServer app cannot be opened in macOS Monterey. For reference, there is no problem opening version 1.5b7. Would you mind to have a look into the latest version of the app?

**Comment by naturale0** [comment]
@iftekharAmurad It wasn't the mail plugin issue, but thank you for your help! The issue did not occurred with the latest stable version.

**Comment by iftekharAmurad** [comment]
🙂
